"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GT8Rwhx1rn2b3KrNYfMtM-XCoX2Ulciv
"""

import pickle
import os
import random
import re
import numpy as np
import tensorflow as tf

train = '/home/tim/Documents/code/python/ultrazvok/train/'
train_path = '/media/tim/Elements/ultrazvok/files/train/'
val_path = '/media/tim/Elements/ultrazvok/files/val/'
test_path = '/media/tim/Elements/ultrazvok/files/test/'

train_path = 'sample_data/train/'

def generator(filepath):
    for _, _, files in os.walk(filepath):
        for file in files:
          try:
              pattern = r"metadata"
              if re.search(pattern, file):
                  continue
              # yield file
              with open(filepath + file, "rb") as file:
                  arr = pickle.load(file)
                  yield np.array(arr)
          except StopIteration:
            break;
               
# change these parameters
batch_size = 64
train_steps=10000/batch_size

train_generator = generator(train_path)
val_generator = generator(val_path)